
# THIS SCRIPT WAS GENERATED BY AI: ORIGINAL SCRIPT IS similarity_study.py


"""
Publication-quality cosine similarity distribution plot for adversarial examples.
Generates a single PDF figure with side-by-side FGSM and PGD distributions.

Usage:
    python plot_cosine_similarity.py
    
Output:
    cosine_similarity_distributions.pdf
"""

import numpy as np 
import matplotlib.pyplot as plt 
import torch
import torchvision
from torchvision import transforms
from sklearn.metrics.pairwise import cosine_similarity
from tqdm import tqdm

# =============================================================================
# Configuration
# =============================================================================

plt.rcParams.update({
    'font.family': 'serif',
    'font.serif': ['Times New Roman', 'DejaVu Serif'],
    'font.size': 10,
    'axes.labelsize': 11,
    'axes.titlesize': 11,
    'xtick.labelsize': 9,
    'ytick.labelsize': 9,
    'legend.fontsize': 9,
    'figure.dpi': 300,
    'savefig.dpi': 300,
    'savefig.bbox': 'tight',
    'savefig.pad_inches': 0.05,
    'axes.linewidth': 0.8,
    'grid.linewidth': 0.5,
    'lines.linewidth': 1.5,
})

# Color scheme matching paper figures
COLORS = {
    'fgsm': '#E74C3C',      # Red
    'pgd': '#3498DB',       # Blue
    'fgsm_edge': '#C0392B', # Darker red
    'pgd_edge': '#2980B9',  # Darker blue
}

# Paths - UPDATE THESE FOR YOUR SYSTEM
CIFAR10_ROOT = '../Datasets/'
FGSM_PATH = "/home/achraf/Research/MLHACK_PAPER/Datasets/CIFAR10-FSGM-eps8.npy"
PGD_PATH = "/home/achraf/Research/MLHACK_PAPER/Datasets/CIFAR10-PGD-eps8.npy"
OUTPUT_PATH = "/home/achraf/Research/MLHACK_PAPER/Figures/cosine_similarity_distributions.pdf"
EPSILON = "8/255"  # For title - change to "8/255" if using eps8 data


# =============================================================================
# Functions
# =============================================================================

def compute_similarities(trainloader, images_fgsm, images_pgd):
    """Compute cosine similarities between original and adversarial images."""
    fgsm_sim = []
    pgd_sim = []
    
    j = 0
    for batch in tqdm(trainloader, desc="Computing similarities"):
        for img in batch[0]:
            orig_flat = img.numpy().flatten().reshape(1, -1)
            fgsm_flat = images_fgsm[j].flatten().reshape(1, -1)
            pgd_flat = images_pgd[j].flatten().reshape(1, -1)
            
            fgsm_sim.append(cosine_similarity(orig_flat, fgsm_flat)[0, 0])
            pgd_sim.append(cosine_similarity(orig_flat, pgd_flat)[0, 0])
            j += 1
    
    return np.array(fgsm_sim), np.array(pgd_sim)


def plot_similarity_distributions(fgsm_sim, pgd_sim, epsilon, output_path):
    """
    Create a publication-quality figure with side-by-side histograms
    comparing FGSM and PGD cosine similarity distributions.
    """
    fig, axes = plt.subplots(1, 2, figsize=(7, 2.8), sharey=True)
    
    # Determine bin range based on data
    min_val = min(fgsm_sim.min(), pgd_sim.min())
    bin_start = max(0.5, min_val - 0.01)
    bins = np.linspace(bin_start, 1.0, 50)
    
    # FGSM subplot
    ax1 = axes[0]
    ax1.hist(
        fgsm_sim, 
        bins=bins, 
        color=COLORS['fgsm'], 
        edgecolor=COLORS['fgsm_edge'],
        alpha=0.8,
        linewidth=0.5
    )
    ax1.axvline(
        x=np.mean(fgsm_sim), 
        color='black', 
        linestyle='--', 
        linewidth=1.2,
        label=f'Mean = {np.mean(fgsm_sim):.4f}'
    )
    ax1.set_xlabel('Cosine Similarity')
    ax1.set_ylabel('Frequency')
    ax1.set_title(f'(a) FGSM ($\\epsilon = {epsilon}$)')
    ax1.legend(loc='upper left', framealpha=0.9)
    ax1.set_xlim(bin_start, 1.0)
    ax1.grid(True, alpha=0.3, linestyle='-', linewidth=0.5)
    ax1.spines['top'].set_visible(False)
    ax1.spines['right'].set_visible(False)
    
    # PGD subplot
    ax2 = axes[1]
    ax2.hist(
        pgd_sim, 
        bins=bins, 
        color=COLORS['pgd'], 
        edgecolor=COLORS['pgd_edge'],
        alpha=0.8,
        linewidth=0.5
    )
    ax2.axvline(
        x=np.mean(pgd_sim), 
        color='black', 
        linestyle='--', 
        linewidth=1.2,
        label=f'Mean = {np.mean(pgd_sim):.4f}'
    )
    ax2.set_xlabel('Cosine Similarity')
    ax2.set_title(f'(b) PGD ($\\epsilon = {epsilon}$)')
    ax2.legend(loc='upper left', framealpha=0.9)
    ax2.set_xlim(bin_start, 1.0)
    ax2.grid(True, alpha=0.3, linestyle='-', linewidth=0.5)
    ax2.spines['top'].set_visible(False)
    ax2.spines['right'].set_visible(False)
    
    plt.tight_layout()
    plt.savefig(output_path, format='pdf', bbox_inches='tight', pad_inches=0.02)
    print(f"Saved: {output_path}")
    
    # Also save PNG for quick preview
    png_path = output_path.replace('.pdf', '.png')
    plt.savefig(png_path, format='png', bbox_inches='tight', pad_inches=0.02)
    print(f"Saved: {png_path}")
    
    plt.close()
    
    # Print statistics
    print(f"\nStatistics:")
    print(f"  FGSM: mean={np.mean(fgsm_sim):.4f}, std={np.std(fgsm_sim):.4f}, min={np.min(fgsm_sim):.4f}")
    print(f"  PGD:  mean={np.mean(pgd_sim):.4f}, std={np.std(pgd_sim):.4f}, min={np.min(pgd_sim):.4f}")


# =============================================================================
# Main
# =============================================================================

if __name__ == "__main__":
    print("Loading CIFAR-10 dataset...")
    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Resize(64),
    ])

    trainset = torchvision.datasets.CIFAR10(
        root=CIFAR10_ROOT, train=True, download=False, transform=transform
    )
    trainloader = torch.utils.data.DataLoader(
        trainset, batch_size=64, shuffle=False
    )
    
    print("Loading adversarial images...")
    images_fgsm = np.load(FGSM_PATH)
    images_pgd = np.load(PGD_PATH)
    
    print(f"FGSM shape: {images_fgsm.shape}")
    print(f"PGD shape: {images_pgd.shape}")
    
    print("\nComputing cosine similarities...")
    fgsm_sim, pgd_sim = compute_similarities(trainloader, images_fgsm, images_pgd)
    
    print("\nGenerating plot...")
    plot_similarity_distributions(fgsm_sim, pgd_sim, EPSILON, OUTPUT_PATH)
    
    print("\nDone!")